version: '3'

services:
  hyppo:
    build:
      context: ./app
      dockerfile: ./hyppo.dockerfile
    deploy:
      mode: replicated
      replicas: 1
    env_file:
      - .env
    ports:
      - "80:80"
