version: '3'
services:
  hyppo:
    image: takez0o/hyppo:0.1.0
    deploy:
      mode: replicated
      replicas: 1
    env_file:
      - .env
  redis:
    image: 'redis:alpine'
    command:
      redis-server
    environment:
     - REDIS_REPLICATION_MODE=master
    volumes:
      - .redis/:/var/lib/redis
  caddy:
    image: takez0o/hyppo-caddy:1.0.0
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .caddy_data:/data
      - .caddy_config:/config
volumes:
  .caddy_data:
    external: true
  .caddy_config:
